### ISSUE TITLE
Getting error in Saiku and also Example code

### ISSUE THREAD

**Issue by makamuni** [mustangore/thesis#4]
Hi ,
I have followed the steps which http://gree2.github.io/bi/2016/01/20/kylin-mondrian-saiku-interaction article

Jars i am using are for Example java  :
kylin-jdbc-1.0-incubating.jar
olap4j.1.2
mondrian-4.4-lagunitas-SNAPSHOT-with-kylin-dialect

I am getting below error in example java class.

Exception in thread "main" java.lang.NoClassDefFoundError: mondrian/xmla/XmlaHandler$XmlaExtra
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:195)
    at TestM.main(TestM.java:14)
Caused by: java.lang.ClassNotFoundException: mondrian.xmla.XmlaHandler$XmlaExtra

In Saiku  it is giving not able to connect to Kylin

Can please help out.

**Comment by JohnForYang** [comment]
Mondrian 4 depends on olap4j-xmlaserver.
however, I meet another problem: No realization found for rel#155039: OLAPTableScan.OLAP.[]...
